services:
  redis:
    image: redis
    ports:
      - '6379:6379'
  web:
    build:
      context: .
    environment:
      FLASK_APP: app
      FLASK_DEBUG: 1
    volumes:
      - .:/app
    env_file: .env
    command: flask run -h 0.0.0.0
    ports:
      - 5000:5000
    depends_on:
      - redis
      - celery
  celery:
    build:
        context: .
    environment:
      FLASK_APP: app
    volumes:
      - .:/app
    env_file: .env
    command: celery -A tasks worker --loglevel=info
    depends_on:
      - redis